# Generated by Django 4.0.4 on 2022-04-14 20:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAP_AUTH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'City'), (2, 'Country'), (3, 'User')], default=3)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('owner', models.ManyToManyField(blank=True, null=True, related_name='parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel',
            },
        ),
        migrations.DeleteModel(
            name='CustomerParcel',
        ),
    ]
