# Generated by Django 4.0.4 on 2022-04-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAP_AUTH', '0003_alter_parcel_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
