# Generated by Django 4.0.3 on 2022-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_parcel_customerparcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparcel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
