# Generated by Django 4.0.4 on 2022-04-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAP_PARCEL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='raster_tiff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=500)),
                ('elevation_max', models.FloatField(default=0)),
                ('elevation_min', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('scale', models.FloatField(default=0.00027777778)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MAP_PARCEL.parcel')),
            ],
            options={
                'db_table': 'rastertiff',
            },
        ),
        migrations.CreateModel(
            name='raster_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=500)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAP_RASTER.raster_tiff')),
            ],
            options={
                'db_table': 'rasterimage',
            },
        ),
    ]
