# Generated by Django 4.0.4 on 2022-04-17 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAP_RASTER', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster_image',
            name='raster',
        ),
        migrations.AddField(
            model_name='raster_image',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raster_tiff',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='raster_tiff',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='raster_tiff',
            name='raster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MAP_RASTER.raster_image'),
        ),
    ]
