# Generated by Django 4.0.4 on 2022-04-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAP_RASTER', '0002_remove_raster_image_raster_raster_image_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster_image',
            name='user',
        ),
    ]
