# Generated by Django 4.0.4 on 2022-04-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAP_RASTER', '0005_remove_raster_tiff_raster_image_raster_image_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster_image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
