# Generated by Django 4.0.4 on 2022-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAP_RASTER', '0006_raster_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster_image',
            name='xmlURL',
            field=models.CharField(default='', max_length=500),
        ),
    ]
